CREATE TABLE ingredient (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  is_meat BOOLEAN,
  is_animal_originated BOOLEAN,
  CONSTRAINT pk_ingredient PRIMARY KEY (id)
);

CREATE TABLE recipe (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  text TEXT,
  CONSTRAINT pk_recipe PRIMARY KEY (id)
);

CREATE TABLE recipe_ingredient (
  amount DOUBLE PRECISION NOT NULL,
  ingredient_fk BIGINT NOT NULL,
  recipe_fk BIGINT NOT NULL,
  unity_of_measure_fk BIGINT NOT NULL,
  CONSTRAINT pk_recipe_ingredient PRIMARY KEY (ingredient_fk, recipe_fk, unity_of_measure_fk)
);

CREATE TABLE unity_of_measure (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_unity_of_measure PRIMARY KEY (id)
);

ALTER TABLE ingredient ADD CONSTRAINT uc_ingredient_name UNIQUE (name);

ALTER TABLE recipe ADD CONSTRAINT uc_recipe_name UNIQUE (name);

ALTER TABLE unity_of_measure ADD CONSTRAINT uc_unity_of_measure_name UNIQUE (name);

ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_RECIPE_INGREDIENT_ON_INGREDIENT_FK FOREIGN KEY (ingredient_fk) REFERENCES ingredient (id);

ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_RECIPE_INGREDIENT_ON_RECIPE_FK FOREIGN KEY (recipe_fk) REFERENCES recipe (id);

ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_RECIPE_INGREDIENT_ON_UNITY_OF_MEASURE_FK FOREIGN KEY (unity_of_measure_fk) REFERENCES unity_of_measure (id);